#!/bin/bash
abort() {
  echo -e "\e[31m$@\e[0m" && exit
}
show() {
  echo -e "\e[32m$1\e[0m doomed!" && exit
}
case $1 in
  you)
    name="$2"
    killall -9 "$name" &> /dev/null || abort 'Noone to fuck!'
    show "$name"
    ;;
  *)
    echo 'Usage: fuck you name' ;;
esac
